import articles from '@/content/help-articles.json'

// Content ships as static JSON generated by `npm run export:content` in the
// backend, so there is no API to call — but the shape the views consume is
// unchanged from when this read Strapi over HTTP.
const wrap = (item) => ({
  id: item.documentId,
  documentId: item.documentId,
  attributes: item,
})

export const helpArticlesService = {
  // Get all articles
  async getAll() {
    return { data: articles.map(wrap) }
  },

  // Get single article by ID
  async getById(id) {
    const item = articles.find((article) => article.documentId === id)
    if (!item) throw new Error(`Article not found: ${id}`)
    return { data: wrap(item) }
  },

  // Get single article by slug
  async getBySlug(slug) {
    const item = articles.find((article) => article.slug === slug)
    if (!item) throw new Error(`Article not found: ${slug}`)
    return { data: wrap(item) }
  },

  // Search articles
  async search(query) {
    const needle = String(query || '').toLowerCase()
    const matches = articles.filter((article) =>
      String(article.title || '').toLowerCase().includes(needle)
    )
    return { data: matches.map(wrap) }
  },
}
